"""Hashline: content-hash anchors for file line editing.

Inspired by oh-my-pi's hashline edit format. Each line gets a
2-char hash anchor that serves as both an address and a staleness
check.

Format: ``{line_number}#{hash}:{original_line}``
Example: ``42#RK:    def foo(self):``

Uses Rust acceleration when available (via _code_puppy_core),
falls back to a pure Python implementation that uses ``zlib.crc32``.

.. warning::
    The Python fallback uses ``zlib.crc32`` rather than ``xxHash32``,
    so its hash values are **not compatible** with those produced by
    the Rust implementation.  Both variants still provide reliable
    staleness detection; you just cannot mix anchors generated by
    one backend with a validator running the other backend.
"""


import re
import zlib

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

NIBBLE_STR = "ZPMQVRWSNKTXJBYH"

# ---------------------------------------------------------------------------
# Attempt Rust acceleration
# ---------------------------------------------------------------------------

_USING_RUST: bool = False

try:
    from _code_puppy_core import (
        compute_line_hash as _rust_compute_line_hash,
        format_hashlines as _rust_format_hashlines,
        strip_hashline_prefixes as _rust_strip_hashline_prefixes,
        validate_hashline_anchor as _rust_validate_hashline_anchor,
    )
    _USING_RUST = True
except ImportError:
    _rust_compute_line_hash = None
    _rust_format_hashlines = None
    _rust_strip_hashline_prefixes = None
    _rust_validate_hashline_anchor = None

# ---------------------------------------------------------------------------
# Regex for stripping hashline prefixes
# ---------------------------------------------------------------------------

_HASHLINE_PREFIX_RE = re.compile(r"^\d+#[A-Z]{2}:(.*)", re.DOTALL)

# ---------------------------------------------------------------------------
# Pure-Python fallback implementations
# ---------------------------------------------------------------------------


def _py_compute_line_hash(idx: int, line: str) -> str:
    """Pure-Python fallback using ``zlib.crc32`` instead of xxHash32.

    The algorithm mirrors the Rust version except the hash primitive:
    - Strip trailing whitespace / ``\\r``
    - If no alphanumeric characters: seed = idx, else seed = 0
    - ``zlib.crc32(bytes, seed) & 0xFF`` → encode low byte via NIBBLE_STR

    .. note::
        Hash values produced here are NOT compatible with those from the
        Rust implementation (which uses xxHash32).
    """
    # Strip trailing whitespace and \\r (mirrors Rust trim_end_matches)
    cleaned = line.rstrip("\r \t\n\x0b\x0c")

    has_alnum = any(c.isalnum() for c in cleaned)
    seed = 0 if has_alnum else idx

    # zlib.crc32 uses a running checksum; passing seed as starting value
    # gives us per-line differentiation for blank/punctuation lines.
    raw = zlib.crc32(cleaned.encode("utf-8"), seed) & 0xFFFFFFFF

    byte = raw & 0xFF
    hi = NIBBLE_STR[(byte >> 4) & 0xF]
    lo = NIBBLE_STR[byte & 0xF]
    return hi + lo


def _py_format_hashlines(text: str, start_line: int = 1) -> str:
    """Pure-Python fallback for :func:`format_hashlines`."""
    parts: list[str] = []
    for i, line in enumerate(text.split("\n")):
        line_num = start_line + i
        h = _py_compute_line_hash(line_num, line)
        parts.append(f"{line_num}#{h}:{line}")
    return "\n".join(parts)


def _py_strip_hashline_prefixes(text: str) -> str:
    """Pure-Python fallback for :func:`strip_hashline_prefixes`."""
    result: list[str] = []
    for line in text.split("\n"):
        m = _HASHLINE_PREFIX_RE.match(line)
        result.append(m.group(1) if m else line)
    return "\n".join(result)


def _py_validate_hashline_anchor(idx: int, line: str, expected_hash: str) -> bool:
    """Pure-Python fallback for :func:`validate_hashline_anchor`."""
    return _py_compute_line_hash(idx, line) == expected_hash


# ---------------------------------------------------------------------------
# Public API  (dispatch to Rust or Python depending on availability)
# ---------------------------------------------------------------------------


def compute_line_hash(idx: int, line: str) -> str:
    """Return a 2-character hash anchor for *line* at 1-based index *idx*.

    The returned string consists of two uppercase characters drawn from
    :data:`NIBBLE_STR`.

    Args:
        idx:  1-based line number used as the hash seed for
              blank/punctuation-only lines.
        line: Raw line content (trailing whitespace is ignored).

    Returns:
        Two-character uppercase hash string, e.g. ``"RK"``.
    """
    if _USING_RUST and _rust_compute_line_hash is not None:
        return _rust_compute_line_hash(idx, line)
    return _py_compute_line_hash(idx, line)


def format_hashlines(text: str, start_line: int = 1) -> str:
    """Prefix every line in *text* with a hashline anchor.

    Each line becomes ``{line_number}#{hash}:{original_line}``.

    Args:
        text:       Multi-line string to annotate.
        start_line: 1-based number of the first line (default ``1``).

    Returns:
        Annotated text with the same number of lines as *text*.
    """
    if _USING_RUST and _rust_format_hashlines is not None:
        return _rust_format_hashlines(text, start_line)
    return _py_format_hashlines(text, start_line)


def strip_hashline_prefixes(text: str) -> str:
    """Remove hashline prefixes from *text*, returning the plain content.

    Lines that do NOT match the ``^\\d+#[A-Z]{2}:`` pattern pass through
    unchanged, so it is safe to call this on partially-annotated text.

    Args:
        text: Text that may contain hashline-prefixed lines.

    Returns:
        Text with all hashline prefixes removed.
    """
    if _USING_RUST and _rust_strip_hashline_prefixes is not None:
        return _rust_strip_hashline_prefixes(text)
    return _py_strip_hashline_prefixes(text)


def validate_hashline_anchor(idx: int, line: str, expected_hash: str) -> bool:
    """Check whether *expected_hash* still matches *line* at index *idx*.

    Returns ``True`` if the content is unchanged; ``False`` if the line
    has been modified since the anchor was recorded (staleness detected).

    Args:
        idx:           1-based line number (same value used when the
                       anchor was originally computed).
        line:          Current line content.
        expected_hash: 2-character hash string to compare against.

    Returns:
        ``True`` if the hashes agree, ``False`` otherwise.
    """
    if _USING_RUST and _rust_validate_hashline_anchor is not None:
        return _rust_validate_hashline_anchor(idx, line, expected_hash)
    return _py_validate_hashline_anchor(idx, line, expected_hash)


def is_using_rust() -> bool:
    """Return ``True`` if the Rust acceleration is active for this module.

    The Rust backend produces hashes compatible with other Rust-backed
    tools; the Python backend uses ``zlib.crc32`` and is not cross-
    compatible.
    """
    return _USING_RUST
