defmodule Mana.Plugins.UniversalConstructor.Engine do
  @moduledoc """
  Core engine for the Universal Constructor.

  Creates, validates, and manages runtime-generated agents and tools.
  Agents are stored as JSON in `~/.mana/agents/`, tools as Elixir
  modules in `~/.mana/data/uc_tools/`.

  ## Operations

    - `create_agent/1` — generate and persist a JSON agent definition
    - `create_tool/1` — generate and persist an Elixir tool module
    - `list_creations/0` — enumerate all UC-created artifacts
    - `delete_creation/2` — remove a UC-created artifact
  """

  require Logger

  alias Mana.Plugins.UniversalConstructor.Template

  @uc_agent_marker "\"_uc_created\""
  @uc_tool_marker "Auto-generated by Universal Constructor"

  # ---------------------------------------------------------------------------
  # Public API
  # ---------------------------------------------------------------------------

  @doc """
  Creates a new agent from a spec map and writes it to `~/.mana/agents/<name>.json`.
  Required fields: `"name"`, `"description"`, `"system_prompt"`.
  """
  @spec create_agent(map()) :: {:ok, String.t()} | {:error, String.t()}
  def create_agent(spec) do
    with {:ok, config} <- Template.agent_json_template(spec),
         :ok <- validate_no_duplicate(config["name"], Template.agent_path(config["name"])),
         path = Template.agent_path(config["name"]),
         :ok <- ensure_dir(Path.dirname(path)),
         :ok <- write_file(path, encode_agent(config)) do
      Logger.info("[UC] Created agent: #{config["name"]} at #{path}")
      {:ok, path}
    end
  end

  @doc """
  Creates a new tool module from a spec map and writes it to `~/.mana/data/uc_tools/<name>.ex`.
  Required fields: `"name"`, `"description"`.
  """
  @spec create_tool(map()) :: {:ok, String.t()} | {:error, String.t()}
  def create_tool(spec) do
    with {:ok, source} <- Template.tool_module_template(spec),
         :ok <- validate_syntax(source),
         :ok <- validate_no_duplicate(spec["name"], Template.tool_path(spec["name"])),
         path = Template.tool_path(spec["name"]),
         :ok <- ensure_dir(Path.dirname(path)),
         :ok <- write_file(path, source) do
      Logger.info("[UC] Created tool: #{spec["name"]} at #{path}")
      {:ok, path}
    end
  end

  @doc """
  Lists all UC-created agents and tools.
  """
  @spec list_creations() :: %{agents: [map()], tools: [map()]}
  def list_creations do
    %{
      agents: scan_dir(Path.expand("~/.mana/agents"), ".json", :agent, &uc_agent?/1),
      tools: scan_dir(Template.user_tools_dir(), ".ex", :tool, &uc_tool?/1)
    }
  end

  @doc """
  Deletes a UC-created artifact by name and type (`:agent` or `:tool`).
  """
  @spec delete_creation(String.t(), :agent | :tool) :: :ok | {:error, String.t()}
  def delete_creation(name, type) do
    path = if type == :agent, do: Template.agent_path(name), else: Template.tool_path(name)
    marker_check = if type == :agent, do: &uc_agent?/1, else: &uc_tool?/1

    cond do
      not File.exists?(path) ->
        {:error, "#{String.capitalize(to_string(type))} not found: #{name}"}

      not marker_check.(path) ->
        {:error, "Not a UC-created #{type}: #{name}"}

      true ->
        case File.rm(path) do
          :ok ->
            Logger.info("[UC] Deleted #{type}: #{name}")
            :ok

          {:error, reason} ->
            {:error, "Failed to delete: #{inspect(reason)}"}
        end
    end
  end

  # ---------------------------------------------------------------------------
  # Scanning & Markers
  # ---------------------------------------------------------------------------

  defp scan_dir(dir, ext, type, marker_fn) do
    case File.ls(dir) do
      {:ok, files} ->
        files
        |> Enum.filter(&String.ends_with?(&1, ext))
        |> Enum.map(&Path.join(dir, &1))
        |> Enum.filter(marker_fn)
        |> Enum.map(fn path ->
          basename = Path.basename(path, ext)
          %{name: basename, path: path, type: type}
        end)

      {:error, _} ->
        []
    end
  end

  defp uc_agent?(path) do
    case File.read(path) do
      {:ok, content} -> String.contains?(content, @uc_agent_marker)
      _ -> false
    end
  end

  defp uc_tool?(path) do
    case File.read(path) do
      {:ok, content} -> String.contains?(content, @uc_tool_marker)
      _ -> false
    end
  end

  # ---------------------------------------------------------------------------
  # Validation
  # ---------------------------------------------------------------------------

  defp validate_no_duplicate(name, path) do
    if File.exists?(path), do: {:error, "Already exists: #{name} (#{path})"}, else: :ok
  end

  defp validate_syntax(source) do
    case Code.string_to_quoted(source) do
      {:ok, _} -> :ok
      {:error, {line, error, token}} -> {:error, "Syntax error at line #{line}: #{error} #{token}"}
    end
  end

  # ---------------------------------------------------------------------------
  # File Helpers
  # ---------------------------------------------------------------------------

  defp ensure_dir(dir) do
    case File.mkdir_p(dir) do
      :ok -> :ok
      {:error, reason} -> {:error, "Cannot create directory #{dir}: #{inspect(reason)}"}
    end
  end

  defp write_file(path, content) do
    case File.write(path, content) do
      :ok -> :ok
      {:error, reason} -> {:error, "Cannot write #{path}: #{inspect(reason)}"}
    end
  end

  defp encode_agent(config) do
    config
    |> Map.put("_uc_created", DateTime.utc_now() |> DateTime.to_iso8601())
    |> Jason.encode!(pretty: true)
  end
end
