"""Marker-based file merge utility for managed content sections.

This module provides functions to write and read content sections demarcated by
HTML-style markers. It supports idempotent updates - calling write_with_markers
twice with the same content produces the same file.
"""

import re
from pathlib import Path
from typing import Optional

from code_puppy.persistence import atomic_write_text


def _make_markers(marker_tag: str) -> tuple[str, str]:
    """Generate start and end markers for a given tag.

    Args:
        marker_tag: The tag to use in markers (will be escaped for regex safety)

    Returns:
        Tuple of (start_marker, end_marker) strings
    """
    start = f"<!-- {marker_tag}:START — Auto-generated by Code Puppy. Do not edit below. -->"
    end = f"<!-- {marker_tag}:END -->"
    return start, end


def _escape_for_regex(text: str) -> str:
    """Escape special regex characters in text for safe pattern matching.

    Args:
        text: The text to escape

    Returns:
        Escaped text safe for use in regex patterns
    """
    return re.escape(text)


def write_with_markers(
    path: Path, content: str, marker_tag: str, placeholder: Optional[str] = None
) -> None:
    """Write content to a file with marker-based section management.

    Handles three cases:
    1. File does not exist → create it with optional placeholder text THEN the marked section
    2. File exists WITHOUT markers → append the marked section at the bottom
    3. File exists WITH markers → replace ONLY the content between the markers

    The markers use HTML comment style and survive round-trips:
        <!-- {marker_tag}:START — Auto-generated by Code Puppy. Do not edit below. -->
        {content}
        <!-- {marker_tag}:END -->

    This function is idempotent: calling it twice with the same content produces
    the same result as calling it once.

    Args:
        path: Path to the file to write
        content: The content to write between markers
        marker_tag: Tag to identify this managed section (used in markers)
        placeholder: Optional text to include before the marked section for new files

    Raises:
        OSError: If the atomic write fails
    """
    path = Path(path)
    start_marker, end_marker = _make_markers(marker_tag)

    # Build the marked section
    marked_section = f"{start_marker}\n{content}\n{end_marker}"

    if not path.exists():
        # Case 1: File does not exist
        if placeholder is not None:
            final_content = f"{placeholder}\n{marked_section}"
        else:
            final_content = marked_section
        atomic_write_text(path, final_content)
        return

    # File exists - read existing content
    existing_content = path.read_text(encoding="utf-8")

    # Check if markers already exist (Case 3)
    escaped_start = _escape_for_regex(start_marker)
    escaped_end = _escape_for_regex(end_marker)

    # Pattern matches anything between start and end markers (including newlines)
    # Uses DOTALL flag so . matches newlines
    pattern = re.compile(
        f"({escaped_start})\\n?(.*?)(\\n?{escaped_end})",
        re.DOTALL,
    )

    if pattern.search(existing_content):
        # Case 3: Replace only the managed section
        # We use a function for replacement to properly handle the content
        def replace_section(match: re.Match) -> str:
            # match.group(1) = start marker (with its newline if present)
            # match.group(2) = old content between markers
            # match.group(3) = end marker (with its newline if present)
            return f"{start_marker}\n{content}\n{end_marker}"

        final_content = pattern.sub(replace_section, existing_content)
    else:
        # Case 2: File exists without markers - append at bottom
        # Add a newline separator if file doesn't end with one
        if existing_content and not existing_content.endswith("\n"):
            existing_content += "\n"
        final_content = f"{existing_content}{marked_section}"

    atomic_write_text(path, final_content)


def read_managed_section(path: Path, marker_tag: str) -> Optional[str]:
    """Read the content between markers from a file.

    Args:
        path: Path to the file to read
        marker_tag: Tag identifying the managed section

    Returns:
        The content between markers, or None if:
        - The file doesn't exist
        - The markers don't exist in the file
        - The section is empty
    """
    path = Path(path)

    if not path.exists():
        return None

    content = path.read_text(encoding="utf-8")
    start_marker, end_marker = _make_markers(marker_tag)

    escaped_start = _escape_for_regex(start_marker)
    escaped_end = _escape_for_regex(end_marker)

    pattern = re.compile(
        f"{escaped_start}\\n?(.*?)(\\n?{escaped_end})",
        re.DOTALL,
    )

    match = pattern.search(content)
    if match:
        return match.group(1)

    return None
