defmodule Mana.Plugins.UniversalConstructor.Template do
  @moduledoc """
  Templates for generating agent JSON definitions and Elixir tool modules.

  Produces valid artifacts that conform to:
  - Agent JSON format expected by `Mana.Agents.JsonLoader`
  - Elixir module format implementing `Mana.Tools.Behaviour`
  """

  alias Mana.Config.Paths

  # ---------------------------------------------------------------------------
  # Agent JSON Template
  # ---------------------------------------------------------------------------

  @doc """
  Generates a valid agent JSON map from a spec.

  Required: `"name"`, `"description"`, `"system_prompt"`.
  Optional: `"display_name"`, `"available_tools"`, `"user_prompt"`, `"tools_config"`.
  """
  @spec agent_json_template(map()) :: {:ok, map()} | {:error, String.t()}
  def agent_json_template(spec) do
    with {:ok, name} <- require_field(spec, "name"),
         {:ok, description} <- require_field(spec, "description"),
         {:ok, system_prompt} <- require_field(spec, "system_prompt"),
         :ok <- validate_agent_name(name) do
      {:ok,
       %{
         "name" => name,
         "display_name" => Map.get(spec, "display_name", humanize(name)),
         "description" => description,
         "system_prompt" => system_prompt,
         "available_tools" => Map.get(spec, "available_tools", default_tools()),
         "user_prompt" => Map.get(spec, "user_prompt", "How can I help?"),
         "tools_config" => Map.get(spec, "tools_config", %{}),
         "load_prompt" => Map.get(spec, "load_prompt", true)
       }}
    end
  end

  # ---------------------------------------------------------------------------
  # Tool Module Template
  # ---------------------------------------------------------------------------

  @doc """
  Generates an Elixir module source string implementing `Mana.Tools.Behaviour`.

  Required: `"name"`, `"description"`.
  Optional: `"parameters"` (JSON Schema props), `"required"` (list), `"module_name"`, `"execute_body"`.
  """
  @spec tool_module_template(map()) :: {:ok, String.t()} | {:error, String.t()}
  def tool_module_template(spec) do
    with {:ok, name} <- require_field(spec, "name"),
         {:ok, description} <- require_field(spec, "description"),
         :ok <- validate_tool_name(name) do
      module = Map.get(spec, "module_name", "Mana.Tools.Uc.#{camelize(name)}")
      params = Map.get(spec, "parameters", %{})
      required = Map.get(spec, "required", [])
      body = Map.get(spec, "execute_body", ~s({:ok, "Tool executed successfully"}))

      {:ok, build_source(module, name, description, params, required, body)}
    end
  end

  # ---------------------------------------------------------------------------
  # Path Helpers
  # ---------------------------------------------------------------------------

  @doc "Returns the path for a user-created agent JSON file."
  @spec agent_path(String.t()) :: String.t()
  def agent_path(name) do
    Path.join(Path.expand("~/.mana/agents"), sanitize(name, ~r/[^a-z0-9_-]/) <> ".json")
  end

  @doc "Returns the path for a user-created tool module file."
  @spec tool_path(String.t()) :: String.t()
  def tool_path(name) do
    Path.join(user_tools_dir(), sanitize(name, ~r/[^a-z0-9_]/) <> ".ex")
  end

  @doc "Returns the user tools directory path."
  @spec user_tools_dir() :: String.t()
  def user_tools_dir, do: Path.join(Paths.data_dir(), "uc_tools")

  # ---------------------------------------------------------------------------
  # Source Builder
  # ---------------------------------------------------------------------------

  defp build_source(module, name, description, params, required, body) do
    schema = build_schema(params, required)
    pattern = build_pattern(params)

    """
    defmodule #{module} do
      @moduledoc \"\"\"
      #{description}

      Auto-generated by Universal Constructor.
      \"\"\"

      @behaviour Mana.Tools.Behaviour

      @impl true
      def name, do: "#{name}"

      @impl true
      def description, do: #{inspect(description)}"

      @impl true
      def parameters do
        #{schema}
      end

      @impl true
      def execute(%{#{pattern}}) do
        #{body}
      end

      def execute(_args) do
        {:error, "Invalid arguments for #{name}"}
      end
    end
    """
    |> String.trim_trailing()
  end

  defp build_schema(params, _required) when map_size(params) == 0 do
    "%{type: \"object\", properties: %{}, required: []}"
  end

  defp build_schema(params, required) do
    props = Enum.map_join(params, ", ", fn {k, v} -> "#{k}: #{inspect(v)}" end)
    "%{type: \"object\", properties: %{#{props}}, required: #{inspect(required)}}"
  end

  defp build_pattern(params) when map_size(params) == 0, do: ""

  defp build_pattern(params) do
    Enum.map_join(Map.keys(params), ", ", fn k -> ~s("#{k}" => #{String.to_atom(k)}) end)
  end

  # ---------------------------------------------------------------------------
  # Validation Helpers
  # ---------------------------------------------------------------------------

  defp require_field(spec, field) do
    case Map.get(spec, field) do
      nil -> {:error, "Missing required field: #{field}"}
      "" -> {:error, "Field '#{field}' cannot be empty"}
      v when is_binary(v) -> {:ok, v}
      _ -> {:error, "Field '#{field}' must be a string"}
    end
  end

  defp validate_agent_name(name) do
    if name =~ ~r/^[a-z][a-z0-9_-]*$/,
      do: :ok,
      else: {:error, "Agent name must be lowercase alphanumeric with hyphens/underscores, starting with a letter"}
  end

  defp validate_tool_name(name) do
    if name =~ ~r/^[a-z][a-z0-9_]*$/,
      do: :ok,
      else: {:error, "Tool name must be lowercase snake_case, starting with a letter"}
  end

  defp sanitize(name, regex), do: String.replace(name, regex, "")
  defp camelize(name), do: Macro.camelize(name)
  defp humanize(name), do: name |> String.split(~r/[-_]/) |> Enum.map_join(" ", &String.capitalize/1)

  defp default_tools do
    ~w(list_files read_file create_file replace_in_file delete_snippet grep run_shell_command ask_user_question)
  end
end
